name: Build

on:
  push:
    branches:
      - developer
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - developer
  schedule:
    - cron: '0 1 * * *'

jobs:
  build-jar:
    uses: samply/github-workflows/.github/workflows/maven.yml@main
    with:
      publish: false
      java-version: 17
      artifact-name: "jar"
      artifact-path: "target/teiler-core.jar"
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      OSSRH_GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
      OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

  build-image:
    needs:
      - build-jar
    uses: samply/github-workflows/.github/workflows/docker-ci.yml@main
    with:
      image-name: 'samply/teiler-core'
      artifact-name: 'jar'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}